package com.lh.entity;

public class DccAreas {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dcc_areas.id
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dcc_areas.areaid
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dcc_areas.area
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dcc_areas.cityid
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String cityid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dcc_areas.id
     *
     * @return the value of dcc_areas.id
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dcc_areas.id
     *
     * @param id the value for dcc_areas.id
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dcc_areas.areaid
     *
     * @return the value of dcc_areas.areaid
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dcc_areas.areaid
     *
     * @param areaid the value for dcc_areas.areaid
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setAreaid(String areaid) {
        this.areaid = areaid == null ? null : areaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dcc_areas.area
     *
     * @return the value of dcc_areas.area
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dcc_areas.area
     *
     * @param area the value for dcc_areas.area
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dcc_areas.cityid
     *
     * @return the value of dcc_areas.cityid
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getCityid() {
        return cityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dcc_areas.cityid
     *
     * @param cityid the value for dcc_areas.cityid
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setCityid(String cityid) {
        this.cityid = cityid == null ? null : cityid.trim();
    }
}