package com.lh.entity;

import java.util.Date;

public class MsDesc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_desc.descId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Long descid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_desc.serviceDesc
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Integer servicedesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_desc.houseDesc
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Integer housedesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_desc.picture
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String picture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_desc.description
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_desc.roomId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Long roomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_desc.userId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_desc.createTime
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_desc.descId
     *
     * @return the value of ms_desc.descId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Long getDescid() {
        return descid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_desc.descId
     *
     * @param descid the value for ms_desc.descId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setDescid(Long descid) {
        this.descid = descid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_desc.serviceDesc
     *
     * @return the value of ms_desc.serviceDesc
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Integer getServicedesc() {
        return servicedesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_desc.serviceDesc
     *
     * @param servicedesc the value for ms_desc.serviceDesc
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setServicedesc(Integer servicedesc) {
        this.servicedesc = servicedesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_desc.houseDesc
     *
     * @return the value of ms_desc.houseDesc
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Integer getHousedesc() {
        return housedesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_desc.houseDesc
     *
     * @param housedesc the value for ms_desc.houseDesc
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setHousedesc(Integer housedesc) {
        this.housedesc = housedesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_desc.picture
     *
     * @return the value of ms_desc.picture
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_desc.picture
     *
     * @param picture the value for ms_desc.picture
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_desc.description
     *
     * @return the value of ms_desc.description
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_desc.description
     *
     * @param description the value for ms_desc.description
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_desc.roomId
     *
     * @return the value of ms_desc.roomId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Long getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_desc.roomId
     *
     * @param roomid the value for ms_desc.roomId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setRoomid(Long roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_desc.userId
     *
     * @return the value of ms_desc.userId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_desc.userId
     *
     * @param userid the value for ms_desc.userId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_desc.createTime
     *
     * @return the value of ms_desc.createTime
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_desc.createTime
     *
     * @param createtime the value for ms_desc.createTime
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}