package com.lh.entity;

import java.util.Date;

public class MsReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_report.repordId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Long repordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_report.userId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_report.type
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_report.reason
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_report.text
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_report.comId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Long comid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_report.createTime
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Date createtime;


    private String username;

    private String phone;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_report.repordId
     *
     * @return the value of ms_report.repordId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Long getRepordid() {
        return repordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_report.repordId
     *
     * @param repordid the value for ms_report.repordId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setRepordid(Long repordid) {
        this.repordid = repordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_report.userId
     *
     * @return the value of ms_report.userId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_report.userId
     *
     * @param userid the value for ms_report.userId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_report.type
     *
     * @return the value of ms_report.type
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_report.type
     *
     * @param type the value for ms_report.type
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_report.reason
     *
     * @return the value of ms_report.reason
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_report.reason
     *
     * @param reason the value for ms_report.reason
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_report.text
     *
     * @return the value of ms_report.text
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_report.text
     *
     * @param text the value for ms_report.text
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_report.comId
     *
     * @return the value of ms_report.comId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Long getComid() {
        return comid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_report.comId
     *
     * @param comid the value for ms_report.comId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setComid(Long comid) {
        this.comid = comid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_report.createTime
     *
     * @return the value of ms_report.createTime
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_report.createTime
     *
     * @param createtime the value for ms_report.createTime
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}