package com.lh.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MsRoomExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ms_room
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ms_room
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ms_room
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_room
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public MsRoomExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_room
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_room
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_room
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_room
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_room
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_room
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_room
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_room
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_room
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_room
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ms_room
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRoomidIsNull() {
            addCriterion("roomId is null");
            return (Criteria) this;
        }

        public Criteria andRoomidIsNotNull() {
            addCriterion("roomId is not null");
            return (Criteria) this;
        }

        public Criteria andRoomidEqualTo(Long value) {
            addCriterion("roomId =", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidNotEqualTo(Long value) {
            addCriterion("roomId <>", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidGreaterThan(Long value) {
            addCriterion("roomId >", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidGreaterThanOrEqualTo(Long value) {
            addCriterion("roomId >=", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidLessThan(Long value) {
            addCriterion("roomId <", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidLessThanOrEqualTo(Long value) {
            addCriterion("roomId <=", value, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidIn(List<Long> values) {
            addCriterion("roomId in", values, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidNotIn(List<Long> values) {
            addCriterion("roomId not in", values, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidBetween(Long value1, Long value2) {
            addCriterion("roomId between", value1, value2, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomidNotBetween(Long value1, Long value2) {
            addCriterion("roomId not between", value1, value2, "roomid");
            return (Criteria) this;
        }

        public Criteria andRoomnameIsNull() {
            addCriterion("roomName is null");
            return (Criteria) this;
        }

        public Criteria andRoomnameIsNotNull() {
            addCriterion("roomName is not null");
            return (Criteria) this;
        }

        public Criteria andRoomnameEqualTo(String value) {
            addCriterion("roomName =", value, "roomname");
            return (Criteria) this;
        }

        public Criteria andRoomnameNotEqualTo(String value) {
            addCriterion("roomName <>", value, "roomname");
            return (Criteria) this;
        }

        public Criteria andRoomnameGreaterThan(String value) {
            addCriterion("roomName >", value, "roomname");
            return (Criteria) this;
        }

        public Criteria andRoomnameGreaterThanOrEqualTo(String value) {
            addCriterion("roomName >=", value, "roomname");
            return (Criteria) this;
        }

        public Criteria andRoomnameLessThan(String value) {
            addCriterion("roomName <", value, "roomname");
            return (Criteria) this;
        }

        public Criteria andRoomnameLessThanOrEqualTo(String value) {
            addCriterion("roomName <=", value, "roomname");
            return (Criteria) this;
        }

        public Criteria andRoomnameLike(String value) {
            addCriterion("roomName like", value, "roomname");
            return (Criteria) this;
        }

        public Criteria andRoomnameNotLike(String value) {
            addCriterion("roomName not like", value, "roomname");
            return (Criteria) this;
        }

        public Criteria andRoomnameIn(List<String> values) {
            addCriterion("roomName in", values, "roomname");
            return (Criteria) this;
        }

        public Criteria andRoomnameNotIn(List<String> values) {
            addCriterion("roomName not in", values, "roomname");
            return (Criteria) this;
        }

        public Criteria andRoomnameBetween(String value1, String value2) {
            addCriterion("roomName between", value1, value2, "roomname");
            return (Criteria) this;
        }

        public Criteria andRoomnameNotBetween(String value1, String value2) {
            addCriterion("roomName not between", value1, value2, "roomname");
            return (Criteria) this;
        }

        public Criteria andRoomimgIsNull() {
            addCriterion("roomImg is null");
            return (Criteria) this;
        }

        public Criteria andRoomimgIsNotNull() {
            addCriterion("roomImg is not null");
            return (Criteria) this;
        }

        public Criteria andRoomimgEqualTo(String value) {
            addCriterion("roomImg =", value, "roomimg");
            return (Criteria) this;
        }

        public Criteria andRoomimgNotEqualTo(String value) {
            addCriterion("roomImg <>", value, "roomimg");
            return (Criteria) this;
        }

        public Criteria andRoomimgGreaterThan(String value) {
            addCriterion("roomImg >", value, "roomimg");
            return (Criteria) this;
        }

        public Criteria andRoomimgGreaterThanOrEqualTo(String value) {
            addCriterion("roomImg >=", value, "roomimg");
            return (Criteria) this;
        }

        public Criteria andRoomimgLessThan(String value) {
            addCriterion("roomImg <", value, "roomimg");
            return (Criteria) this;
        }

        public Criteria andRoomimgLessThanOrEqualTo(String value) {
            addCriterion("roomImg <=", value, "roomimg");
            return (Criteria) this;
        }

        public Criteria andRoomimgLike(String value) {
            addCriterion("roomImg like", value, "roomimg");
            return (Criteria) this;
        }

        public Criteria andRoomimgNotLike(String value) {
            addCriterion("roomImg not like", value, "roomimg");
            return (Criteria) this;
        }

        public Criteria andRoomimgIn(List<String> values) {
            addCriterion("roomImg in", values, "roomimg");
            return (Criteria) this;
        }

        public Criteria andRoomimgNotIn(List<String> values) {
            addCriterion("roomImg not in", values, "roomimg");
            return (Criteria) this;
        }

        public Criteria andRoomimgBetween(String value1, String value2) {
            addCriterion("roomImg between", value1, value2, "roomimg");
            return (Criteria) this;
        }

        public Criteria andRoomimgNotBetween(String value1, String value2) {
            addCriterion("roomImg not between", value1, value2, "roomimg");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andAreaIsNull() {
            addCriterion("area is null");
            return (Criteria) this;
        }

        public Criteria andAreaIsNotNull() {
            addCriterion("area is not null");
            return (Criteria) this;
        }

        public Criteria andAreaEqualTo(String value) {
            addCriterion("area =", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotEqualTo(String value) {
            addCriterion("area <>", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThan(String value) {
            addCriterion("area >", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaGreaterThanOrEqualTo(String value) {
            addCriterion("area >=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThan(String value) {
            addCriterion("area <", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLessThanOrEqualTo(String value) {
            addCriterion("area <=", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaLike(String value) {
            addCriterion("area like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotLike(String value) {
            addCriterion("area not like", value, "area");
            return (Criteria) this;
        }

        public Criteria andAreaIn(List<String> values) {
            addCriterion("area in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotIn(List<String> values) {
            addCriterion("area not in", values, "area");
            return (Criteria) this;
        }

        public Criteria andAreaBetween(String value1, String value2) {
            addCriterion("area between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andAreaNotBetween(String value1, String value2) {
            addCriterion("area not between", value1, value2, "area");
            return (Criteria) this;
        }

        public Criteria andDoormodelIsNull() {
            addCriterion("doormodel is null");
            return (Criteria) this;
        }

        public Criteria andDoormodelIsNotNull() {
            addCriterion("doormodel is not null");
            return (Criteria) this;
        }

        public Criteria andDoormodelEqualTo(String value) {
            addCriterion("doormodel =", value, "doormodel");
            return (Criteria) this;
        }

        public Criteria andDoormodelNotEqualTo(String value) {
            addCriterion("doormodel <>", value, "doormodel");
            return (Criteria) this;
        }

        public Criteria andDoormodelGreaterThan(String value) {
            addCriterion("doormodel >", value, "doormodel");
            return (Criteria) this;
        }

        public Criteria andDoormodelGreaterThanOrEqualTo(String value) {
            addCriterion("doormodel >=", value, "doormodel");
            return (Criteria) this;
        }

        public Criteria andDoormodelLessThan(String value) {
            addCriterion("doormodel <", value, "doormodel");
            return (Criteria) this;
        }

        public Criteria andDoormodelLessThanOrEqualTo(String value) {
            addCriterion("doormodel <=", value, "doormodel");
            return (Criteria) this;
        }

        public Criteria andDoormodelLike(String value) {
            addCriterion("doormodel like", value, "doormodel");
            return (Criteria) this;
        }

        public Criteria andDoormodelNotLike(String value) {
            addCriterion("doormodel not like", value, "doormodel");
            return (Criteria) this;
        }

        public Criteria andDoormodelIn(List<String> values) {
            addCriterion("doormodel in", values, "doormodel");
            return (Criteria) this;
        }

        public Criteria andDoormodelNotIn(List<String> values) {
            addCriterion("doormodel not in", values, "doormodel");
            return (Criteria) this;
        }

        public Criteria andDoormodelBetween(String value1, String value2) {
            addCriterion("doormodel between", value1, value2, "doormodel");
            return (Criteria) this;
        }

        public Criteria andDoormodelNotBetween(String value1, String value2) {
            addCriterion("doormodel not between", value1, value2, "doormodel");
            return (Criteria) this;
        }

        public Criteria andCompanionIsNull() {
            addCriterion("companion is null");
            return (Criteria) this;
        }

        public Criteria andCompanionIsNotNull() {
            addCriterion("companion is not null");
            return (Criteria) this;
        }

        public Criteria andCompanionEqualTo(Integer value) {
            addCriterion("companion =", value, "companion");
            return (Criteria) this;
        }

        public Criteria andCompanionNotEqualTo(Integer value) {
            addCriterion("companion <>", value, "companion");
            return (Criteria) this;
        }

        public Criteria andCompanionGreaterThan(Integer value) {
            addCriterion("companion >", value, "companion");
            return (Criteria) this;
        }

        public Criteria andCompanionGreaterThanOrEqualTo(Integer value) {
            addCriterion("companion >=", value, "companion");
            return (Criteria) this;
        }

        public Criteria andCompanionLessThan(Integer value) {
            addCriterion("companion <", value, "companion");
            return (Criteria) this;
        }

        public Criteria andCompanionLessThanOrEqualTo(Integer value) {
            addCriterion("companion <=", value, "companion");
            return (Criteria) this;
        }

        public Criteria andCompanionIn(List<Integer> values) {
            addCriterion("companion in", values, "companion");
            return (Criteria) this;
        }

        public Criteria andCompanionNotIn(List<Integer> values) {
            addCriterion("companion not in", values, "companion");
            return (Criteria) this;
        }

        public Criteria andCompanionBetween(Integer value1, Integer value2) {
            addCriterion("companion between", value1, value2, "companion");
            return (Criteria) this;
        }

        public Criteria andCompanionNotBetween(Integer value1, Integer value2) {
            addCriterion("companion not between", value1, value2, "companion");
            return (Criteria) this;
        }

        public Criteria andBedtypeIsNull() {
            addCriterion("bedType is null");
            return (Criteria) this;
        }

        public Criteria andBedtypeIsNotNull() {
            addCriterion("bedType is not null");
            return (Criteria) this;
        }

        public Criteria andBedtypeEqualTo(String value) {
            addCriterion("bedType =", value, "bedtype");
            return (Criteria) this;
        }

        public Criteria andBedtypeNotEqualTo(String value) {
            addCriterion("bedType <>", value, "bedtype");
            return (Criteria) this;
        }

        public Criteria andBedtypeGreaterThan(String value) {
            addCriterion("bedType >", value, "bedtype");
            return (Criteria) this;
        }

        public Criteria andBedtypeGreaterThanOrEqualTo(String value) {
            addCriterion("bedType >=", value, "bedtype");
            return (Criteria) this;
        }

        public Criteria andBedtypeLessThan(String value) {
            addCriterion("bedType <", value, "bedtype");
            return (Criteria) this;
        }

        public Criteria andBedtypeLessThanOrEqualTo(String value) {
            addCriterion("bedType <=", value, "bedtype");
            return (Criteria) this;
        }

        public Criteria andBedtypeLike(String value) {
            addCriterion("bedType like", value, "bedtype");
            return (Criteria) this;
        }

        public Criteria andBedtypeNotLike(String value) {
            addCriterion("bedType not like", value, "bedtype");
            return (Criteria) this;
        }

        public Criteria andBedtypeIn(List<String> values) {
            addCriterion("bedType in", values, "bedtype");
            return (Criteria) this;
        }

        public Criteria andBedtypeNotIn(List<String> values) {
            addCriterion("bedType not in", values, "bedtype");
            return (Criteria) this;
        }

        public Criteria andBedtypeBetween(String value1, String value2) {
            addCriterion("bedType between", value1, value2, "bedtype");
            return (Criteria) this;
        }

        public Criteria andBedtypeNotBetween(String value1, String value2) {
            addCriterion("bedType not between", value1, value2, "bedtype");
            return (Criteria) this;
        }

        public Criteria andBedsizeIsNull() {
            addCriterion("bedSize is null");
            return (Criteria) this;
        }

        public Criteria andBedsizeIsNotNull() {
            addCriterion("bedSize is not null");
            return (Criteria) this;
        }

        public Criteria andBedsizeEqualTo(String value) {
            addCriterion("bedSize =", value, "bedsize");
            return (Criteria) this;
        }

        public Criteria andBedsizeNotEqualTo(String value) {
            addCriterion("bedSize <>", value, "bedsize");
            return (Criteria) this;
        }

        public Criteria andBedsizeGreaterThan(String value) {
            addCriterion("bedSize >", value, "bedsize");
            return (Criteria) this;
        }

        public Criteria andBedsizeGreaterThanOrEqualTo(String value) {
            addCriterion("bedSize >=", value, "bedsize");
            return (Criteria) this;
        }

        public Criteria andBedsizeLessThan(String value) {
            addCriterion("bedSize <", value, "bedsize");
            return (Criteria) this;
        }

        public Criteria andBedsizeLessThanOrEqualTo(String value) {
            addCriterion("bedSize <=", value, "bedsize");
            return (Criteria) this;
        }

        public Criteria andBedsizeLike(String value) {
            addCriterion("bedSize like", value, "bedsize");
            return (Criteria) this;
        }

        public Criteria andBedsizeNotLike(String value) {
            addCriterion("bedSize not like", value, "bedsize");
            return (Criteria) this;
        }

        public Criteria andBedsizeIn(List<String> values) {
            addCriterion("bedSize in", values, "bedsize");
            return (Criteria) this;
        }

        public Criteria andBedsizeNotIn(List<String> values) {
            addCriterion("bedSize not in", values, "bedsize");
            return (Criteria) this;
        }

        public Criteria andBedsizeBetween(String value1, String value2) {
            addCriterion("bedSize between", value1, value2, "bedsize");
            return (Criteria) this;
        }

        public Criteria andBedsizeNotBetween(String value1, String value2) {
            addCriterion("bedSize not between", value1, value2, "bedsize");
            return (Criteria) this;
        }

        public Criteria andFacilityIsNull() {
            addCriterion("facility is null");
            return (Criteria) this;
        }

        public Criteria andFacilityIsNotNull() {
            addCriterion("facility is not null");
            return (Criteria) this;
        }

        public Criteria andFacilityEqualTo(String value) {
            addCriterion("facility =", value, "facility");
            return (Criteria) this;
        }

        public Criteria andFacilityNotEqualTo(String value) {
            addCriterion("facility <>", value, "facility");
            return (Criteria) this;
        }

        public Criteria andFacilityGreaterThan(String value) {
            addCriterion("facility >", value, "facility");
            return (Criteria) this;
        }

        public Criteria andFacilityGreaterThanOrEqualTo(String value) {
            addCriterion("facility >=", value, "facility");
            return (Criteria) this;
        }

        public Criteria andFacilityLessThan(String value) {
            addCriterion("facility <", value, "facility");
            return (Criteria) this;
        }

        public Criteria andFacilityLessThanOrEqualTo(String value) {
            addCriterion("facility <=", value, "facility");
            return (Criteria) this;
        }

        public Criteria andFacilityLike(String value) {
            addCriterion("facility like", value, "facility");
            return (Criteria) this;
        }

        public Criteria andFacilityNotLike(String value) {
            addCriterion("facility not like", value, "facility");
            return (Criteria) this;
        }

        public Criteria andFacilityIn(List<String> values) {
            addCriterion("facility in", values, "facility");
            return (Criteria) this;
        }

        public Criteria andFacilityNotIn(List<String> values) {
            addCriterion("facility not in", values, "facility");
            return (Criteria) this;
        }

        public Criteria andFacilityBetween(String value1, String value2) {
            addCriterion("facility between", value1, value2, "facility");
            return (Criteria) this;
        }

        public Criteria andFacilityNotBetween(String value1, String value2) {
            addCriterion("facility not between", value1, value2, "facility");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAreasnearIsNull() {
            addCriterion("areasNear is null");
            return (Criteria) this;
        }

        public Criteria andAreasnearIsNotNull() {
            addCriterion("areasNear is not null");
            return (Criteria) this;
        }

        public Criteria andAreasnearEqualTo(String value) {
            addCriterion("areasNear =", value, "areasnear");
            return (Criteria) this;
        }

        public Criteria andAreasnearNotEqualTo(String value) {
            addCriterion("areasNear <>", value, "areasnear");
            return (Criteria) this;
        }

        public Criteria andAreasnearGreaterThan(String value) {
            addCriterion("areasNear >", value, "areasnear");
            return (Criteria) this;
        }

        public Criteria andAreasnearGreaterThanOrEqualTo(String value) {
            addCriterion("areasNear >=", value, "areasnear");
            return (Criteria) this;
        }

        public Criteria andAreasnearLessThan(String value) {
            addCriterion("areasNear <", value, "areasnear");
            return (Criteria) this;
        }

        public Criteria andAreasnearLessThanOrEqualTo(String value) {
            addCriterion("areasNear <=", value, "areasnear");
            return (Criteria) this;
        }

        public Criteria andAreasnearLike(String value) {
            addCriterion("areasNear like", value, "areasnear");
            return (Criteria) this;
        }

        public Criteria andAreasnearNotLike(String value) {
            addCriterion("areasNear not like", value, "areasnear");
            return (Criteria) this;
        }

        public Criteria andAreasnearIn(List<String> values) {
            addCriterion("areasNear in", values, "areasnear");
            return (Criteria) this;
        }

        public Criteria andAreasnearNotIn(List<String> values) {
            addCriterion("areasNear not in", values, "areasnear");
            return (Criteria) this;
        }

        public Criteria andAreasnearBetween(String value1, String value2) {
            addCriterion("areasNear between", value1, value2, "areasnear");
            return (Criteria) this;
        }

        public Criteria andAreasnearNotBetween(String value1, String value2) {
            addCriterion("areasNear not between", value1, value2, "areasnear");
            return (Criteria) this;
        }

        public Criteria andRoomnumIsNull() {
            addCriterion("roomNum is null");
            return (Criteria) this;
        }

        public Criteria andRoomnumIsNotNull() {
            addCriterion("roomNum is not null");
            return (Criteria) this;
        }

        public Criteria andRoomnumEqualTo(Integer value) {
            addCriterion("roomNum =", value, "roomnum");
            return (Criteria) this;
        }

        public Criteria andRoomnumNotEqualTo(Integer value) {
            addCriterion("roomNum <>", value, "roomnum");
            return (Criteria) this;
        }

        public Criteria andRoomnumGreaterThan(Integer value) {
            addCriterion("roomNum >", value, "roomnum");
            return (Criteria) this;
        }

        public Criteria andRoomnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("roomNum >=", value, "roomnum");
            return (Criteria) this;
        }

        public Criteria andRoomnumLessThan(Integer value) {
            addCriterion("roomNum <", value, "roomnum");
            return (Criteria) this;
        }

        public Criteria andRoomnumLessThanOrEqualTo(Integer value) {
            addCriterion("roomNum <=", value, "roomnum");
            return (Criteria) this;
        }

        public Criteria andRoomnumIn(List<Integer> values) {
            addCriterion("roomNum in", values, "roomnum");
            return (Criteria) this;
        }

        public Criteria andRoomnumNotIn(List<Integer> values) {
            addCriterion("roomNum not in", values, "roomnum");
            return (Criteria) this;
        }

        public Criteria andRoomnumBetween(Integer value1, Integer value2) {
            addCriterion("roomNum between", value1, value2, "roomnum");
            return (Criteria) this;
        }

        public Criteria andRoomnumNotBetween(Integer value1, Integer value2) {
            addCriterion("roomNum not between", value1, value2, "roomnum");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Long value) {
            addCriterion("userId =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Long value) {
            addCriterion("userId <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Long value) {
            addCriterion("userId >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Long value) {
            addCriterion("userId >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Long value) {
            addCriterion("userId <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Long value) {
            addCriterion("userId <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Long> values) {
            addCriterion("userId in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Long> values) {
            addCriterion("userId not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Long value1, Long value2) {
            addCriterion("userId between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Long value1, Long value2) {
            addCriterion("userId not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andHosingscoreIsNull() {
            addCriterion("hosingScore is null");
            return (Criteria) this;
        }

        public Criteria andHosingscoreIsNotNull() {
            addCriterion("hosingScore is not null");
            return (Criteria) this;
        }

        public Criteria andHosingscoreEqualTo(Long value) {
            addCriterion("hosingScore =", value, "hosingscore");
            return (Criteria) this;
        }

        public Criteria andHosingscoreNotEqualTo(Long value) {
            addCriterion("hosingScore <>", value, "hosingscore");
            return (Criteria) this;
        }

        public Criteria andHosingscoreGreaterThan(Long value) {
            addCriterion("hosingScore >", value, "hosingscore");
            return (Criteria) this;
        }

        public Criteria andHosingscoreGreaterThanOrEqualTo(Long value) {
            addCriterion("hosingScore >=", value, "hosingscore");
            return (Criteria) this;
        }

        public Criteria andHosingscoreLessThan(Long value) {
            addCriterion("hosingScore <", value, "hosingscore");
            return (Criteria) this;
        }

        public Criteria andHosingscoreLessThanOrEqualTo(Long value) {
            addCriterion("hosingScore <=", value, "hosingscore");
            return (Criteria) this;
        }

        public Criteria andHosingscoreIn(List<Long> values) {
            addCriterion("hosingScore in", values, "hosingscore");
            return (Criteria) this;
        }

        public Criteria andHosingscoreNotIn(List<Long> values) {
            addCriterion("hosingScore not in", values, "hosingscore");
            return (Criteria) this;
        }

        public Criteria andHosingscoreBetween(Long value1, Long value2) {
            addCriterion("hosingScore between", value1, value2, "hosingscore");
            return (Criteria) this;
        }

        public Criteria andHosingscoreNotBetween(Long value1, Long value2) {
            addCriterion("hosingScore not between", value1, value2, "hosingscore");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ms_room
     *
     * @mbggenerated do_not_delete_during_merge Wed May 01 11:04:32 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ms_room
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}