package com.lh.entity;

import java.math.BigDecimal;
import java.util.Date;

public class MsRoom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.roomId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Long roomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.roomName
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String roomname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.roomImg
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String roomimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.type
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.area
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.doormodel
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String doormodel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.companion
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Integer companion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.bedType
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String bedtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.bedSize
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String bedsize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.facility
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String facility;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.address
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.areasNear
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String areasnear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.roomNum
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Integer roomnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.price
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.status
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.userId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.hosingScore
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Long hosingscore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room.createTime
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.roomId
     *
     * @return the value of ms_room.roomId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Long getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.roomId
     *
     * @param roomid the value for ms_room.roomId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setRoomid(Long roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.roomName
     *
     * @return the value of ms_room.roomName
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getRoomname() {
        return roomname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.roomName
     *
     * @param roomname the value for ms_room.roomName
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setRoomname(String roomname) {
        this.roomname = roomname == null ? null : roomname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.roomImg
     *
     * @return the value of ms_room.roomImg
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getRoomimg() {
        return roomimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.roomImg
     *
     * @param roomimg the value for ms_room.roomImg
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setRoomimg(String roomimg) {
        this.roomimg = roomimg == null ? null : roomimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.type
     *
     * @return the value of ms_room.type
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.type
     *
     * @param type the value for ms_room.type
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.area
     *
     * @return the value of ms_room.area
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.area
     *
     * @param area the value for ms_room.area
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.doormodel
     *
     * @return the value of ms_room.doormodel
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getDoormodel() {
        return doormodel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.doormodel
     *
     * @param doormodel the value for ms_room.doormodel
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setDoormodel(String doormodel) {
        this.doormodel = doormodel == null ? null : doormodel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.companion
     *
     * @return the value of ms_room.companion
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Integer getCompanion() {
        return companion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.companion
     *
     * @param companion the value for ms_room.companion
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setCompanion(Integer companion) {
        this.companion = companion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.bedType
     *
     * @return the value of ms_room.bedType
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getBedtype() {
        return bedtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.bedType
     *
     * @param bedtype the value for ms_room.bedType
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setBedtype(String bedtype) {
        this.bedtype = bedtype == null ? null : bedtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.bedSize
     *
     * @return the value of ms_room.bedSize
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getBedsize() {
        return bedsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.bedSize
     *
     * @param bedsize the value for ms_room.bedSize
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setBedsize(String bedsize) {
        this.bedsize = bedsize == null ? null : bedsize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.facility
     *
     * @return the value of ms_room.facility
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getFacility() {
        return facility;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.facility
     *
     * @param facility the value for ms_room.facility
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setFacility(String facility) {
        this.facility = facility == null ? null : facility.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.address
     *
     * @return the value of ms_room.address
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.address
     *
     * @param address the value for ms_room.address
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.areasNear
     *
     * @return the value of ms_room.areasNear
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getAreasnear() {
        return areasnear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.areasNear
     *
     * @param areasnear the value for ms_room.areasNear
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setAreasnear(String areasnear) {
        this.areasnear = areasnear == null ? null : areasnear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.roomNum
     *
     * @return the value of ms_room.roomNum
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Integer getRoomnum() {
        return roomnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.roomNum
     *
     * @param roomnum the value for ms_room.roomNum
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setRoomnum(Integer roomnum) {
        this.roomnum = roomnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.price
     *
     * @return the value of ms_room.price
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.price
     *
     * @param price the value for ms_room.price
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.status
     *
     * @return the value of ms_room.status
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.status
     *
     * @param status the value for ms_room.status
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.userId
     *
     * @return the value of ms_room.userId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.userId
     *
     * @param userid the value for ms_room.userId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.hosingScore
     *
     * @return the value of ms_room.hosingScore
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Long getHosingscore() {
        return hosingscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.hosingScore
     *
     * @param hosingscore the value for ms_room.hosingScore
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setHosingscore(Long hosingscore) {
        this.hosingscore = hosingscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room.createTime
     *
     * @return the value of ms_room.createTime
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room.createTime
     *
     * @param createtime the value for ms_room.createTime
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}