package com.lh.entity;

public class MsRoomNotice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room_notice.id
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room_notice.roomId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Long roomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_room_notice.noticeId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Long noticeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room_notice.id
     *
     * @return the value of ms_room_notice.id
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room_notice.id
     *
     * @param id the value for ms_room_notice.id
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room_notice.roomId
     *
     * @return the value of ms_room_notice.roomId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Long getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room_notice.roomId
     *
     * @param roomid the value for ms_room_notice.roomId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setRoomid(Long roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_room_notice.noticeId
     *
     * @return the value of ms_room_notice.noticeId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Long getNoticeid() {
        return noticeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_room_notice.noticeId
     *
     * @param noticeid the value for ms_room_notice.noticeId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setNoticeid(Long noticeid) {
        this.noticeid = noticeid;
    }
}