package com.lh.entity;

public class MsUserHobby {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user_hobby.id
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user_hobby.userId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user_hobby.hobbyId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Long hobbyid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user_hobby.id
     *
     * @return the value of ms_user_hobby.id
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user_hobby.id
     *
     * @param id the value for ms_user_hobby.id
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user_hobby.userId
     *
     * @return the value of ms_user_hobby.userId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user_hobby.userId
     *
     * @param userid the value for ms_user_hobby.userId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user_hobby.hobbyId
     *
     * @return the value of ms_user_hobby.hobbyId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Long getHobbyid() {
        return hobbyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user_hobby.hobbyId
     *
     * @param hobbyid the value for ms_user_hobby.hobbyId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setHobbyid(Long hobbyid) {
        this.hobbyid = hobbyid;
    }
}