package com.lh.entity;

import java.util.Date;

public class MsUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.userId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.username
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.password
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.realName
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.age
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.sex
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Byte sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.phone
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.type
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.hobby
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String hobby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.email
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.address
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.headPhoto
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String headphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.level
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.integration
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Integer integration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.createTime
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.bankCard
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String bankcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user.sleeperId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Integer sleeperid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.userId
     *
     * @return the value of ms_user.userId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.userId
     *
     * @param userid the value for ms_user.userId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.username
     *
     * @return the value of ms_user.username
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.username
     *
     * @param username the value for ms_user.username
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.password
     *
     * @return the value of ms_user.password
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.password
     *
     * @param password the value for ms_user.password
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.realName
     *
     * @return the value of ms_user.realName
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.realName
     *
     * @param realname the value for ms_user.realName
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.age
     *
     * @return the value of ms_user.age
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.age
     *
     * @param age the value for ms_user.age
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.sex
     *
     * @return the value of ms_user.sex
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.sex
     *
     * @param sex the value for ms_user.sex
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.phone
     *
     * @return the value of ms_user.phone
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.phone
     *
     * @param phone the value for ms_user.phone
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.type
     *
     * @return the value of ms_user.type
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.type
     *
     * @param type the value for ms_user.type
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.hobby
     *
     * @return the value of ms_user.hobby
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getHobby() {
        return hobby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.hobby
     *
     * @param hobby the value for ms_user.hobby
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setHobby(String hobby) {
        this.hobby = hobby == null ? null : hobby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.email
     *
     * @return the value of ms_user.email
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.email
     *
     * @param email the value for ms_user.email
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.address
     *
     * @return the value of ms_user.address
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.address
     *
     * @param address the value for ms_user.address
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.headPhoto
     *
     * @return the value of ms_user.headPhoto
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getHeadphoto() {
        return headphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.headPhoto
     *
     * @param headphoto the value for ms_user.headPhoto
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setHeadphoto(String headphoto) {
        this.headphoto = headphoto == null ? null : headphoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.level
     *
     * @return the value of ms_user.level
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.level
     *
     * @param level the value for ms_user.level
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.integration
     *
     * @return the value of ms_user.integration
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Integer getIntegration() {
        return integration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.integration
     *
     * @param integration the value for ms_user.integration
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setIntegration(Integer integration) {
        this.integration = integration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.createTime
     *
     * @return the value of ms_user.createTime
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.createTime
     *
     * @param createtime the value for ms_user.createTime
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.bankCard
     *
     * @return the value of ms_user.bankCard
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getBankcard() {
        return bankcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.bankCard
     *
     * @param bankcard the value for ms_user.bankCard
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setBankcard(String bankcard) {
        this.bankcard = bankcard == null ? null : bankcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user.sleeperId
     *
     * @return the value of ms_user.sleeperId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Integer getSleeperid() {
        return sleeperid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user.sleeperId
     *
     * @param sleeperid the value for ms_user.sleeperId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setSleeperid(Integer sleeperid) {
        this.sleeperid = sleeperid;
    }
}