package com.lh.entity;

public class MsUserRoom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user_room.id
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user_room.userId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Long userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_user_room.roomId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Long roomid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user_room.id
     *
     * @return the value of ms_user_room.id
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user_room.id
     *
     * @param id the value for ms_user_room.id
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user_room.userId
     *
     * @return the value of ms_user_room.userId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user_room.userId
     *
     * @param userid the value for ms_user_room.userId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_user_room.roomId
     *
     * @return the value of ms_user_room.roomId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Long getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_user_room.roomId
     *
     * @param roomid the value for ms_user_room.roomId
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setRoomid(Long roomid) {
        this.roomid = roomid;
    }
}