package com.lh.entity;

import java.util.Date;

public class SysAdmin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.admin_id
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Long adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.username
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.password
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.email
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.mobile
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.status
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.create_user_id
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Long createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.create_time
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.dept_id
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private Integer deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.sex
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    private String sex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.admin_id
     *
     * @return the value of sys_admin.admin_id
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Long getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.admin_id
     *
     * @param adminId the value for sys_admin.admin_id
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setAdminId(Long adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.username
     *
     * @return the value of sys_admin.username
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.username
     *
     * @param username the value for sys_admin.username
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.password
     *
     * @return the value of sys_admin.password
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.password
     *
     * @param password the value for sys_admin.password
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.email
     *
     * @return the value of sys_admin.email
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.email
     *
     * @param email the value for sys_admin.email
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.mobile
     *
     * @return the value of sys_admin.mobile
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.mobile
     *
     * @param mobile the value for sys_admin.mobile
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.status
     *
     * @return the value of sys_admin.status
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.status
     *
     * @param status the value for sys_admin.status
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.create_user_id
     *
     * @return the value of sys_admin.create_user_id
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Long getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.create_user_id
     *
     * @param createUserId the value for sys_admin.create_user_id
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setCreateUserId(Long createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.create_time
     *
     * @return the value of sys_admin.create_time
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.create_time
     *
     * @param createTime the value for sys_admin.create_time
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.dept_id
     *
     * @return the value of sys_admin.dept_id
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.dept_id
     *
     * @param deptId the value for sys_admin.dept_id
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.sex
     *
     * @return the value of sys_admin.sex
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.sex
     *
     * @param sex the value for sys_admin.sex
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }
}