package com.lh.entity;

import java.util.Date;

public class SysLoginlog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_loginlog.log_id
     *
     * @mbggenerated Fri May 03 20:59:56 CST 2019
     */
    private Integer logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_loginlog.admin_id
     *
     * @mbggenerated Fri May 03 20:59:56 CST 2019
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_loginlog.loginitme
     *
     * @mbggenerated Fri May 03 20:59:56 CST 2019
     */
    private Date loginitme;


    private String adminname;

    public String getAdminname() {
        return adminname;
    }

    public void setAdminname(String adminname) {
        this.adminname = adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_loginlog.log_id
     *
     * @return the value of sys_loginlog.log_id
     *
     * @mbggenerated Fri May 03 20:59:56 CST 2019
     */
    public Integer getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_loginlog.log_id
     *
     * @param logId the value for sys_loginlog.log_id
     *
     * @mbggenerated Fri May 03 20:59:56 CST 2019
     */
    public void setLogId(Integer logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_loginlog.admin_id
     *
     * @return the value of sys_loginlog.admin_id
     *
     * @mbggenerated Fri May 03 20:59:56 CST 2019
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_loginlog.admin_id
     *
     * @param adminId the value for sys_loginlog.admin_id
     *
     * @mbggenerated Fri May 03 20:59:56 CST 2019
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_loginlog.loginitme
     *
     * @return the value of sys_loginlog.loginitme
     *
     * @mbggenerated Fri May 03 20:59:56 CST 2019
     */
    public Date getLoginitme() {
        return loginitme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_loginlog.loginitme
     *
     * @param loginitme the value for sys_loginlog.loginitme
     *
     * @mbggenerated Fri May 03 20:59:56 CST 2019
     */
    public void setLoginitme(Date loginitme) {
        this.loginitme = loginitme;
    }
}