package com.lh.mapper;

import com.lh.entity.DccAreas;
import com.lh.entity.DccAreasExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DccAreasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dcc_areas
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    int countByExample(DccAreasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dcc_areas
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    int deleteByExample(DccAreasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dcc_areas
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dcc_areas
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    int insert(DccAreas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dcc_areas
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    int insertSelective(DccAreas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dcc_areas
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    List<DccAreas> selectByExample(DccAreasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dcc_areas
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    DccAreas selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dcc_areas
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    int updateByExampleSelective(@Param("record") DccAreas record, @Param("example") DccAreasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dcc_areas
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    int updateByExample(@Param("record") DccAreas record, @Param("example") DccAreasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dcc_areas
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    int updateByPrimaryKeySelective(DccAreas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dcc_areas
     *
     * @mbggenerated Wed May 01 11:04:32 CST 2019
     */
    int updateByPrimaryKey(DccAreas record);
}