package com.lh.mapper;

import com.lh.entity.SysAdmin;
import com.lh.entity.SysAdminExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated Tue Apr 30 21:23:43 CST 2019
     */
    int countByExample(SysAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated Tue Apr 30 21:23:43 CST 2019
     */
    int deleteByExample(SysAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated Tue Apr 30 21:23:43 CST 2019
     */
    int deleteByPrimaryKey(Long adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated Tue Apr 30 21:23:43 CST 2019
     */
    int insert(SysAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated Tue Apr 30 21:23:43 CST 2019
     */
    int insertSelective(SysAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated Tue Apr 30 21:23:43 CST 2019
     */
    List<SysAdmin> selectByExample(SysAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated Tue Apr 30 21:23:43 CST 2019
     */
    SysAdmin selectByPrimaryKey(Long adminId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated Tue Apr 30 21:23:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") SysAdmin record, @Param("example") SysAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated Tue Apr 30 21:23:43 CST 2019
     */
    int updateByExample(@Param("record") SysAdmin record, @Param("example") SysAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated Tue Apr 30 21:23:43 CST 2019
     */
    int updateByPrimaryKeySelective(SysAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated Tue Apr 30 21:23:43 CST 2019
     */
    int updateByPrimaryKey(SysAdmin record);
}